// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0p7lvP4Ucc4wBONo6gsZ0VrnKjKJVlk',
    appId: '1:796068114399:web:f609e1f59d5a978d669e6a',
    messagingSenderId: '796068114399',
    projectId: 'myfirstproject-4c178',
    authDomain: 'myfirstproject-4c178.firebaseapp.com',
    storageBucket: 'myfirstproject-4c178.firebasestorage.app',
    measurementId: 'G-YN07P244X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHCiOv7Y0hN2WZPgsLQulqY7oxhHHhBu0',
    appId: '1:796068114399:android:cd147fff045b3452669e6a',
    messagingSenderId: '796068114399',
    projectId: 'myfirstproject-4c178',
    storageBucket: 'myfirstproject-4c178.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYB8yC8wPy4K4lZI-vz5jyfKvWGbwOn60',
    appId: '1:796068114399:ios:5c8e7366ad15c837669e6a',
    messagingSenderId: '796068114399',
    projectId: 'myfirstproject-4c178',
    storageBucket: 'myfirstproject-4c178.firebasestorage.app',
    iosBundleId: 'com.example.finalhackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYB8yC8wPy4K4lZI-vz5jyfKvWGbwOn60',
    appId: '1:796068114399:ios:5c8e7366ad15c837669e6a',
    messagingSenderId: '796068114399',
    projectId: 'myfirstproject-4c178',
    storageBucket: 'myfirstproject-4c178.firebasestorage.app',
    iosBundleId: 'com.example.finalhackathon',
  );

}